[tool.poetry]
name = "pygameimage"
version = "0.1.0"
description = ""
authors = ["Lenacwk <lrsdance4life@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pygame = "^1.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
